{"name": "No se permite agregar más de un cónyuge", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50347): Max retries exceeded with url: /session/916d6c00dcd9d23f0eb67a4313fd5e99/source (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1025797b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/common_steps.py\", line 92, in step_impl\n    assert context.page.validar_mensaje_error_generico(mensaje), \\\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/pages/products/queplan/page.py\", line 33, in validar_mensaje_error_generico\n    return validar_mensaje_en_pantalla(self.driver, mensaje_esperado, timeout)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/validations/common_validations.py\", line 115, in validar_mensaje_en_pantalla\n    print(driver.page_source[:1000])\n          ^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 447, in page_source\n    return self.execute(Command.GET_PAGE_SOURCE)[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/_request_methods.py\", line 135, in request\n    return self.request_encode_url(\n           ~~~~~~~~~~~~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<3 lines>...\n        **urlopen_kw,\n        ^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/_request_methods.py\", line 182, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<13 lines>...\n        **response_kw,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<13 lines>...\n        **response_kw,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<13 lines>...\n        **response_kw,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 841, in urlopen\n    retries = retries.increment(\n        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]\n    )\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/util/retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Given que el usuario accede al formulario de Queplan", "status": "passed", "start": 1752523707305, "stop": 1752523707822}, {"name": "When ingresa datos de contratante con rut \"17470576-3\"", "status": "passed", "start": 1752523707822, "stop": 1752523714248}, {"name": "And ingresa datos de beneficiario con rut \"15046896-5\"", "status": "passed", "start": 1752523714248, "stop": 1752523717249}, {"name": "And agrega otro cónyuge con rut \"6065750-5\"", "status": "passed", "start": 1752523717249, "stop": 1752523721217}, {"name": "And hace clic en Siguiente paso", "status": "passed", "start": 1752523721217, "stop": 1752523721272}, {"name": "Then debe mostrarse el mensaje de error \"Hay más de un perfil con la relación Conyugé. Solo puede haber uno.\"", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50347): Max retries exceeded with url: /session/916d6c00dcd9d23f0eb67a4313fd5e99/source (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1025797b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/common_steps.py\", line 92, in step_impl\n    assert context.page.validar_mensaje_error_generico(mensaje), \\\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/pages/products/queplan/page.py\", line 33, in validar_mensaje_error_generico\n    return validar_mensaje_en_pantalla(self.driver, mensaje_esperado, timeout)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/validations/common_validations.py\", line 115, in validar_mensaje_en_pantalla\n    print(driver.page_source[:1000])\n          ^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 447, in page_source\n    return self.execute(Command.GET_PAGE_SOURCE)[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/_request_methods.py\", line 135, in request\n    return self.request_encode_url(\n           ~~~~~~~~~~~~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<3 lines>...\n        **urlopen_kw,\n        ^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/_request_methods.py\", line 182, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<13 lines>...\n        **response_kw,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<13 lines>...\n        **response_kw,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<13 lines>...\n        **response_kw,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 841, in urlopen\n    retries = retries.increment(\n        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]\n    )\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/util/retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1752523721272, "stop": 1752523727096}], "start": 1752523689782, "stop": 1752523727099, "uuid": "ad309a37-f43a-4fcf-a79a-9d0443cd20e5", "historyId": "2acead2e5bc23ff9b4d5c8548b012223", "fullName": "Flujo completo de contratación de seguro en Queplan: No se permite agregar más de un cónyuge", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "negative"}, {"name": "tag", "value": "queplan"}, {"name": "tag", "value": "regression"}, {"name": "feature", "value": "Flujo completo de contratación de seguro en Queplan"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}