{"uid":"b7e873852ac6df96","name":"No se permite agregar más de un cónyuge","fullName":"Flujo completo de contratación de seguro en Queplan: No se permite agregar más de un cónyuge","historyId":"2acead2e5bc23ff9b4d5c8548b012223","time":{"start":1752523689782,"stop":1752523727099,"duration":37317},"status":"broken","statusMessage":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50347): Max retries exceeded with url: /session/916d6c00dcd9d23f0eb67a4313fd5e99/source (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1025797b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n","statusTrace":"  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/common_steps.py\", line 92, in step_impl\n    assert context.page.validar_mensaje_error_generico(mensaje), \\\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/pages/products/queplan/page.py\", line 33, in validar_mensaje_error_generico\n    return validar_mensaje_en_pantalla(self.driver, mensaje_esperado, timeout)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/validations/common_validations.py\", line 115, in validar_mensaje_en_pantalla\n    print(driver.page_source[:1000])\n          ^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 447, in page_source\n    return self.execute(Command.GET_PAGE_SOURCE)[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/_request_methods.py\", line 135, in request\n    return self.request_encode_url(\n           ~~~~~~~~~~~~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<3 lines>...\n        **urlopen_kw,\n        ^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/_request_methods.py\", line 182, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<13 lines>...\n        **response_kw,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<13 lines>...\n        **response_kw,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<13 lines>...\n        **response_kw,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 841, in urlopen\n    retries = retries.increment(\n        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]\n    )\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/util/retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":4,"retriesStatusChange":true,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50347): Max retries exceeded with url: /session/916d6c00dcd9d23f0eb67a4313fd5e99/source (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1025797b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n","statusTrace":"  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/common_steps.py\", line 92, in step_impl\n    assert context.page.validar_mensaje_error_generico(mensaje), \\\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/pages/products/queplan/page.py\", line 33, in validar_mensaje_error_generico\n    return validar_mensaje_en_pantalla(self.driver, mensaje_esperado, timeout)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/validations/common_validations.py\", line 115, in validar_mensaje_en_pantalla\n    print(driver.page_source[:1000])\n          ^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 447, in page_source\n    return self.execute(Command.GET_PAGE_SOURCE)[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/_request_methods.py\", line 135, in request\n    return self.request_encode_url(\n           ~~~~~~~~~~~~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<3 lines>...\n        **urlopen_kw,\n        ^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/_request_methods.py\", line 182, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<13 lines>...\n        **response_kw,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<13 lines>...\n        **response_kw,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<13 lines>...\n        **response_kw,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 841, in urlopen\n    retries = retries.increment(\n        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]\n    )\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/util/retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[{"name":"Given que el usuario accede al formulario de Queplan","time":{"start":1752523707305,"stop":1752523707822,"duration":517},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"hasContent":false,"attachmentStep":false,"shouldDisplayMessage":false,"attachmentsCount":0},{"name":"When ingresa datos de contratante con rut \"17470576-3\"","time":{"start":1752523707822,"stop":1752523714248,"duration":6426},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"hasContent":false,"attachmentStep":false,"shouldDisplayMessage":false,"attachmentsCount":0},{"name":"And ingresa datos de beneficiario con rut \"15046896-5\"","time":{"start":1752523714248,"stop":1752523717249,"duration":3001},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"hasContent":false,"attachmentStep":false,"shouldDisplayMessage":false,"attachmentsCount":0},{"name":"And agrega otro cónyuge con rut \"6065750-5\"","time":{"start":1752523717249,"stop":1752523721217,"duration":3968},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"hasContent":false,"attachmentStep":false,"shouldDisplayMessage":false,"attachmentsCount":0},{"name":"And hace clic en Siguiente paso","time":{"start":1752523721217,"stop":1752523721272,"duration":55},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"hasContent":false,"attachmentStep":false,"shouldDisplayMessage":false,"attachmentsCount":0},{"name":"Then debe mostrarse el mensaje de error \"Hay más de un perfil con la relación Conyugé. Solo puede haber uno.\"","time":{"start":1752523721272,"stop":1752523727096,"duration":5824},"status":"broken","statusMessage":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50347): Max retries exceeded with url: /session/916d6c00dcd9d23f0eb67a4313fd5e99/source (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1025797b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n","statusTrace":"  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/common_steps.py\", line 92, in step_impl\n    assert context.page.validar_mensaje_error_generico(mensaje), \\\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/pages/products/queplan/page.py\", line 33, in validar_mensaje_error_generico\n    return validar_mensaje_en_pantalla(self.driver, mensaje_esperado, timeout)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/validations/common_validations.py\", line 115, in validar_mensaje_en_pantalla\n    print(driver.page_source[:1000])\n          ^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 447, in page_source\n    return self.execute(Command.GET_PAGE_SOURCE)[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/_request_methods.py\", line 135, in request\n    return self.request_encode_url(\n           ~~~~~~~~~~~~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<3 lines>...\n        **urlopen_kw,\n        ^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/_request_methods.py\", line 182, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<13 lines>...\n        **response_kw,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<13 lines>...\n        **response_kw,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ~~~~~~~~~~~~^\n        method,\n        ^^^^^^^\n    ...<13 lines>...\n        **response_kw,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py\", line 841, in urlopen\n    retries = retries.increment(\n        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]\n    )\n  File \"/Users/lauraandrade/PycharmProjects/Pasarela/.venv/lib/python3.13/site-packages/urllib3/util/retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"hasContent":true,"attachmentStep":false,"shouldDisplayMessage":true,"attachmentsCount":0}],"attachments":[],"parameters":[],"stepsCount":6,"hasContent":true,"attachmentStep":false,"shouldDisplayMessage":false,"attachmentsCount":0},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"tag","value":"negative"},{"name":"tag","value":"queplan"},{"name":"tag","value":"regression"},{"name":"feature","value":"Flujo completo de contratación de seguro en Queplan"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"df47e0710415b861","status":"passed","time":{"start":1751990881786,"stop":1751990986620,"duration":104834}},{"uid":"57b4fc32774ae53d","status":"failed","statusDetails":"AssertionError: No se mostró el mensaje 'Hay más de un perfil con la relación Conyugé. Solo puede haber uno.'\n","time":{"start":1751549934951,"stop":1751550032744,"duration":97793}},{"uid":"da3b784239bd7ce7","status":"failed","statusDetails":"AssertionError: No se mostró el mensaje 'Hay más de un perfil con la relación Conyugé. Solo puede haber uno.'\n","time":{"start":1751386169214,"stop":1751386266041,"duration":96827}},{"uid":"3ec9dadbc8009f22","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: \n\n","time":{"start":1751385361954,"stop":1751385385321,"duration":23367}}],"categories":[{"name":"Test defects","matchedStatuses":[]}],"tags":["queplan","negative","regression"]},"source":"b7e873852ac6df96.json","parameterValues":[]}